library("readxl")
library(ggplot2)
my_data <- read_excel("/Users/mit/Desktop/mary.xls", sheet = "Sheet1",na = "---")
Mother <- data.frame(type = "Mother", age = rnorm(n=33, mean = mean(my_data$`M age`), sd = sd(my_data$`M age`)))
Father <- data.frame(type = "Father", age = rnorm(n=33, mean = mean(my_data$`F age`), sd = sd(my_data$`F age`)))
df <- rbind(Mother, Father)
t.test(age ~ type, data = df)
plot(my_data$`F age`,type = "o",col = "red", xlab = "Index", ylab = "Age")
lines(my_data$`M age`, type = "o", col = "blue", lty=2)
